#!/usr/bin/env python
import numpy as np

import rospy
from geometry_msgs.msg import Quaternion, Vector3, Transform, TransformStamped
from sensor_msgs.msg import Imu
from tf.transformations import euler_from_quaternion, quaternion_from_euler, quaternion_multiply
from tf2_ros import (Buffer, TransformListener, TransformBroadcaster, LookupException, ConnectivityException,
                     ExtrapolationException, Header)


def get_param(param_name, default):
    try:
        return rospy.get_param(param_name)
    except KeyError:
        rospy.loginfo("Parameter '%s not set, using default '%s'", param_name, default)
        return default


def xyzw_to_numpy(ori):
    return np.array((ori.x, ori.y, ori.z, ori.w))


class Odom2dPubliser(object):
    def __init__(self):
        self.base_link = get_param('~base_link_frame', 'base_link')
        self.odom = get_param('~odom_frame', 'odom')
        self.odom_2d = get_param('~odom_2d_frame', 'odom_2d')

        self.tf_buffer = Buffer()
        self.listener = TransformListener(self.tf_buffer)

        self.broadcaster = TransformBroadcaster()

        # rospy.loginfo('wait for transform %s -> %s', self.base_link, self.odom)
        # self.tf_buffer.can_transform(self.base_link, self.odom, rospy.Time())

        # fill the tf buffer a little bit
        rospy.sleep(1)

        imu_topic = get_param('~imu_topic', 'imu')
        rospy.Subscriber(imu_topic, Imu, self.imu_callback)

    def imu_callback(self, data):
        imu_frame = data.header.frame_id
        try:
            odom_to_imu = self.tf_buffer.lookup_transform(self.odom, imu_frame, data.header.stamp, rospy.Duration(1))
        except (LookupException, ConnectivityException, ExtrapolationException) as e:
            rospy.logerr_throttle(5, e)
        else:
            q_imu = xyzw_to_numpy(data.orientation)
            q = xyzw_to_numpy(odom_to_imu.transform.rotation)
            q_imu_in_odom = -quaternion_multiply(q, q_imu)

            # _, _, _ = euler_from_quaternion(q)
            # r, p, y = euler_from_quaternion(q_imu_in_odom)
            # q_stable = q_imu_in_odom #quaternion_from_euler(r, p, y)

            rospy.logdebug('q: r=%.2f, p=%.2f, y=%.2f', *euler_from_quaternion(q))
            rospy.logdebug('q_imu: r=%.2f, p=%.2f, y=%.2f', *euler_from_quaternion(q_imu))
            rospy.logdebug('q_stable: r=%.2f, p=%.2f, y=%.2f', *euler_from_quaternion(q_imu_in_odom))

            transform = Transform()
            transform.translation = Vector3()
            transform.rotation = Quaternion(*q_imu_in_odom)
            ts = TransformStamped(header=Header(stamp=data.header.stamp, frame_id=self.odom), child_frame_id = self.odom_2d, transform=transform)
            self.broadcaster.sendTransform(ts)


def main():
    rospy.init_node('odom_2d_publisher', log_level=rospy.DEBUG)
    Odom2dPubliser()
    rospy.spin()


if __name__ == '__main__':
    main()
