before_script:
    # Make sure we can access the docker images repository
    - mkdir ~/.ssh 
    - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

    # Clone the ruvu-env for the docker images
    - git clone git@gitlab.com:ruvu/environment.git ~/.ruvu

kinetic-x86:
    variables:
        PACKAGES: "pepper_hardware ruvu_web ruvu_flexbe_states ruvu_gazebo_plugins ruvu_bringup ruvu_rostest" # Separate with spaces
        DOCKER_FILE: Dockerfile-kinetic-x86
    image: docker:git
    services:
        - docker:dind
    script:
        - cd ~/.ruvu
        - docker build --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" --build-arg PACKAGES="$PACKAGES" --build-arg WORKSPACE="$CI_PROJECT_NAME" -t registry.gitlab.com/ruvu/$CI_PROJECT_NAME/$CI_JOB_NAME -f ~/.ruvu/docker/$DOCKER_FILE .
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker push registry.gitlab.com/ruvu/$CI_PROJECT_NAME/$CI_JOB_NAME:latest
