image: ros:kinetic-ros-core

variables:
  PACKAGES: >-
    ruvu_flexbe_states
    ruvu_web
    ruvu_rqt
    ruvu_gazebo_plugins
    ruvu_sensor_descriptions
    ruvu_bringup
    ruvu_rostest
    ruvu_networkx
    ruvu_msg_converters
    ruvu_mbf
    ruvu_navigation_playground
    ruvu_frame_2d_publisher
    ruvu_rabbitmq_bridge
    ruvu_rviz_plugins
    ruvu_teleop
    pepper_hardware
    pozyx_ros
    pozyx_msgs
    opc_ros
    opc_msgs
  WORKSPACE: $CI_PROJECT_NAME

stages:
  - build

job:
  stage: build

  before_script:
    - apt-get update && apt-get install -y
        git
        python-pip
        ssh
    - pip install ros-get
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

    - git clone git@gitlab.com:ruvu/environment.git ~/.ruvu

  script:
    - mkdir $WORKSPACE
    - ros-get ws-create --name $WORKSPACE --dir $WORKSPACE file://$HOME/.ruvu/rosdistro/$WORKSPACE.yaml /opt/ros/`ls /opt/ros`/
    - source ~/.ruvu/setup.bash
    - rosdep update
    - ros-get install $PACKAGES

    - cd $WORKSPACE
    - catkin build
    - catkin test --summary
