#!/usr/bin/env python

import pika
import argparse
import json

parser = argparse.ArgumentParser(description='Receive rabbitmq json messages from a queue')
parser.add_argument('--host', type=str, default='localhost', help='The RabbitMQ host')
parser.add_argument('--username', type=str, default='', help='The RabbitMQ username')
parser.add_argument('--password', type=str, default='', help='The RabbitMQ password')
parser.add_argument('queue_name', metavar='QUEUE', type=str, help='RabbitMQ queue name')

args = parser.parse_args()

# Setup RabbitMQ connection
if args.username:
    parameters = pika.ConnectionParameters(host=args.host, credentials=pika.PlainCredentials(args.username,
                                                                                             args.password))
else:
    parameters = pika.ConnectionParameters(host=args.host)
connection = pika.BlockingConnection(parameters)
channel = connection.channel()
channel.queue_declare(queue=args.queue_name)


def callback(channel, method, properties, body):
    dictionary = json.loads(body)

    print "-- Received rabbitmq json message:"
    print "Channel: ", channel
    print "Method: ", method
    print "properties: ", properties
    print "body: ", body
    print "dictionary: ", dictionary

channel.basic_consume(callback, queue=args.queue_name, no_ack=True)

print 'Waiting for messages on queue {}. To exit press CTRL+C'.format(args.queue_name)
channel.start_consuming()
