#!/usr/bin/env python

# Copyright 2020 RUVU Robotics B.V.

import rospy
import rostest
import sys
import unittest
from std_srvs.srv import SetBool, SetBoolRequest

PKG = 'rospy_tutorials'
NAME = 'talker_listener_test'


class TestClient(unittest.TestCase):
    def __init__(self, *args):
        super(TestClient, self).__init__(*args)

    def test_client(self):
        rospy.init_node(NAME)
        client = rospy.ServiceProxy('output', SetBool)
        client.wait_for_service()

        ros_msg = SetBoolRequest(data=True)
        response = client(ros_msg)
        self.assert_(response.success)
        self.assert_(response.message == "ok")


if __name__ == '__main__':
    rostest.rosrun(PKG, NAME, TestClient, sys.argv)
