FROM ros:kinetic-ros-core

RUN apt-get update && apt-get install -y python-catkin-tools

# Create ROS workspace
COPY . /ws/src/
WORKDIR /ws

# Install the package and its dependencies
RUN rosdep install --from-paths src --ignore-src --rosdistro kinetic -y

# Set up the development environment
RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash && catkin build"
