#!/usr/bin/env python

import rospy
import tf.transformations as tft
from gazebo_ros import gazebo_interface
from geometry_msgs.msg import Pose, Quaternion

if __name__ == "__main__":
    rospy.init_node('spawn_model')

    initial_pose = Pose()
    initial_pose.position.x = rospy.get_param('initial_pose_x', 0)
    initial_pose.position.y = rospy.get_param('initial_pose_y', 0)
    initial_pose.position.z = rospy.get_param('initial_pose_z', 0)

    initial_pose.orientation = Quaternion(*tft.quaternion_from_euler(rospy.get_param('initial_pose_roll', 0),
                                                                     rospy.get_param('initial_pose_pitch', 0),
                                                                     rospy.get_param('initial_pose_yaw', 0)))

    success = gazebo_interface.spawn_urdf_model_client(rospy.get_param('~robot_name', 'robot'),
                                                       rospy.get_param('robot_description'),
                                                       rospy.get_param('robot_namespace', ''),
                                                       initial_pose,
                                                       rospy.get_param('~reference_frame', ''),
                                                       rospy.get_param('~namespace', '/gazebo'))
