#!/usr/bin/env python

# Copyright 2020 RUVU Robotics B.V.

from collections import namedtuple

import rospy

from std_msgs.msg import Float64
from sensor_msgs.msg import Joy


ButtonAction = namedtuple('ButtonAction', ['axis_index', 'factor', 'publisher'])


def callback(msg):
    for enable_button, action in enable_buttons.items():
        if msg.buttons[enable_button] == 1:
            out_msg = Float64(data=msg.axes[action.axis_index]*action.factor)
        else:
            out_msg = Float64(data=0.0)
        action.publisher.publish(out_msg)


if __name__ == "__main__":
    rospy.init_node('teleop_publish_float_joy')

    button_mapping = rospy.get_param("~button_mapping")

    enable_buttons = {
        int(e["button_index"]):
        ButtonAction(axis_index=int(e["axis_index"]),
                     factor=float(e["factor"]),
                     publisher=rospy.Publisher(e["topic"], Float64, queue_size=1))
        for e in button_mapping
    }

    sub = rospy.Subscriber('joy', Joy, callback, queue_size=1)

    rospy.spin()
