#!/usr/bin/env python

# MIT License
#
# Copyright (c) 2017 RUVU Robotics
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import rospy
import actionlib
from hmi_msgs.msg import CastAction

from pepper_hardware import QiSession


class TextToSpeechServer(object):
    def __init__(self):
        """
        TextToSpeechServer Text to speech server for the Pepper Robot
        """
        self._session = QiSession()
        self._tts = self._session.get_service("ALTextToSpeech")

        self._server = actionlib.SimpleActionServer('text_to_speech', CastAction, self._goal_callback, False)
        self._server.start()

    def _goal_callback(self, goal):
        self._tts.say(goal.message)
        self._server.set_succeeded()


if __name__ == "__main__":
    rospy.init_node("text_to_speech")
    server = TextToSpeechServer()
    rospy.spin()
