#!/usr/bin/env python

# Copyright 2020 RUVU Robotics B.V.

import rospy
from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped


def callback(msg):
    """
    Callback to refactor input msg of type PoseWithCovarianceStamped to output msg of type PoseStamped
    :param msg: Incoming pose with covariance stamped
    """
    ps = PoseStamped()
    ps.header = msg.header
    ps.pose = msg.pose.pose
    pub.publish(ps)


if __name__ == '__main__':
    rospy.init_node("pose_with_covariance_stamped_to_pose_stamped")
    sub = rospy.Subscriber("input", PoseWithCovarianceStamped, callback)
    pub = rospy.Publisher("output", PoseStamped, queue_size=1)

    try:
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
