#!/usr/bin/env python
import os

import actionlib
import rospy
from geometry_msgs.msg import PoseStamped
from mbf_msgs.msg import MoveBaseGoal, MoveBaseAction


def simple_goal_cb(msg):
    rospy.logdebug("Relaying move_base_simple/goal pose to mbf")
    mbf_ac.send_goal(MoveBaseGoal(target_pose=msg,
                                  controller=controller,
                                  planner=planner,
                                  recovery_behaviors=recovery_behaviors))


if __name__ == '__main__':
    rospy.init_node(os.path.basename(__file__))

    controller = rospy.get_param('~controller', None)
    planner = rospy.get_param('~planner', None)
    recovery_behaviors = rospy.get_param('~recovery_behaviors', None)

    mbf_ac = actionlib.SimpleActionClient("move_base", MoveBaseAction)

    while not rospy.is_shutdown() and not mbf_ac.wait_for_server(rospy.Duration(5)):
        rospy.loginfo('waiting for %s', mbf_ac.action_client.ns)

    simple_goal_sub = rospy.Subscriber('simple_goal', PoseStamped, simple_goal_cb)

    rospy.loginfo('%s started', rospy.get_name())
    rospy.spin()
