#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Installing roscore systemd service for user "`whoami`
cp $DIR/../systemd/roscore.service /tmp/roscore.service
echo User=`whoami` >> /tmp/roscore.service
sudo cp "/tmp/roscore.service" "/etc/systemd/system/"

echo "Reloading daemon ..."
sudo systemctl daemon-reload

echo "You can start the service using 'sudo systemctl start roscore.service'"
echo "You can enable the service (on start-up) using 'sudo systemctl enable roscore.service'"

